version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - /home/santiago/postgres:/var/lib/postgresql/data