version: '3.8'

services:

  mongodb:
    container_name: mongodb
    image: mongo:7.0.11
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    container_name: mongo_express
    image: mongo-express:1.0.2-18
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DOCKER_ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DOCKER_ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL_CONNECTION}
    depends_on:
      - mongodb

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DB: ${POSTGRESQL_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: