name: Hotfix Tagging

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  hotfix-versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Generate version, update docs, commit and tag
        run: |
          VERSION="${{ inputs.version }}"
          echo "✔ Detected hotfix version: $VERSION"

          echo "✔ Changing to the scripts directory"
          cd ./scripts

          echo "✔ Running the versioning script"
          ./generate-version.sh "$VERSION"

          git config user.name "CI GoGallery Bot"
          git config user.email "gogalleryteam@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Hotfix version $VERSION"
            git push
          else
            echo "⚠ No changes to commit"
          fi

          git tag -a "$VERSION" -m "Hotfix version $VERSION"
          git push origin "$VERSION"
