name: Hotfix Versioning

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write

jobs:
  hotfix-versioning:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Generate version, update docs, commit and tag
        run: |
          VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's|hotfix/||')
          echo "✔ Detected hotfix version: $VERSION"

          cd ./scripts
          ./generate-version.sh "$VERSION"

          git config user.name "CI GoGallery Bot"
          git config user.email "gogalleryteam@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Hotfix version $VERSION [skip ci]"
            git push
          else
            echo "⚠ No changes to commit"
            exit 0
          fi

          git tag -a "$VERSION" -m "Hotfix version $VERSION"
          git push origin "$VERSION"
