name: Release Versioning on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

  release-versioning:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Versioning and Tagging
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed 's|refs/heads/release/v||')

          echo "✔ Detected release version: $VERSION"
          ./scripts/generate-version.sh

          git config user.name "CI Bot"
          git config user.email "gogalleryteam@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          if [[ -n $(git status --porcelain) ]]; then
            git commit -am "Release version $VERSION [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi

          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"
