name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Check if release branch
        id: check_release
        run: |
          BRANCH_NAME=$(git symbolic-ref --short HEAD)
          echo "Branch: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV 
          if [[ ! "$BRANCH_NAME" =~ ^release/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "Not a valid release branch. Exiting."
            exit 1
          fi
          VERSION="${BASH_REMATCH[1]}"
          echo "Release version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV 

      - name: Build
        run: go build -v ./...

      - name: Check build success
        if: ${{ failure() }}
        run: |
          echo "Build failed. Aborting pipeline."
          exit 1

      - name: Run Tests
        run: go test -v ./...

      - name: Check tests
        if: ${{ failure() }}
        run: |
          echo "Tests failed. Skipping version generation."
          exit 1

      - name: Generate version in the code
        run: |
          ./scripts/generate-version.sh

      - name: Commit version updates
        run: |
          git config user.name "CI Bot"
          git config user.email "ci-bot@example.com"
          git add .
          git commit -m "Update version to ${VERSION} [skip ci]"
          git push origin HEAD:${{ github.head_ref }}

      - name: Merge to main branch
        run: |
          git checkout main
          git merge "${{ env.BRANCH_NAME }}"
          git push origin main

      - name: Generate version tag
        run: |
          VERSION_TAG=v${{ env.VERSION }}
          git tag -a "$VERSION_TAG" -m "Release version $VERSION_TAG"
          git push origin "$VERSION_TAG"
