name: Versioning Release Updates

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  release-versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Generate version, update docs, commit and tag
        run: |
          VERSION="${{ inputs.version }}"

          echo "✔ Detected release version: $VERSION"

          echo "✔ Changing to the scripts directory"
          cd ./scripts

          echo "✔ Running the versioning script"
          ./generate-version.sh "$VERSION"

          git config user.name "CI GoGallery Bot"
          git config user.email "gogalleryteam@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          if [[ -n $(git status --porcelain) ]]; then
            git pull
            git add . 
            git commit -am "Release version $VERSION"
            git push
          else
            echo "⚠ No changes to commit for version $VERSION"
            exit 1 
          fi

          git tag -a "$VERSION" -m "Release version $VERSION"
          git push origin "$VERSION"
      - name: Trigger Docker publish workflow
        run: |
          echo "🚀 Dispatching docker publish for version $VERSION"
          gh workflow run docker-publish.yml -f version="$VERSION"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sanbricio/go-gallery${{ inputs.version }}
